# Basic
title: 刘川   #潘柏信
subtitle: 个人站
description: 欢迎来到我的个人站~
# 头像里面的标题
avatarTitle: cliu_1995    #leopardpan
# 头像里面的描述
avatarDesc: FPGA / 图像处理    #iOS / 机器学习
url: http://lc-img.com/  #"http://baixin.io"

# Comment
comment:
    disqus: cliu_1995
    # gitment: xxx // 需要修改 comments.html中的client_id和client_secret
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    weibo: 5366874726 
    github: lcimage
    # zhihu: panpanleopard
    # juejin: xxx
    jianshu: 2ada30d8d0f7
    # twitter: 
    mail: liuchuan9536@163.com  #leopardpan@icloud.com


# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 6b9ba9290500647f00d3b2c6b6cf9296 

# # Google Analytics
# # 使用博客模板请去掉或者更换 id
# ga:
#     id: xxxx  
#     host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/lcimage/lcimage.github.io   #https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


